In [0]:
import pandas as pd
import numpy as np

In [0]:
data_moex = pd.read_csv('MOEX Russia Historical Data.csv', sep=";").iloc[::-1].reset_index()
data_usdrub = pd.read_csv('USD_RUB Historical Data.csv', index_col='Date').iloc[::-1].reset_index()
data_brent = pd.read_csv('Brent Oil Futures Historical Data.csv', index_col ='Date').iloc[::-1].reset_index()
data_moex['Date'] = pd.to_datetime(data_moex['Date'])
data_usdrub['Date'] = pd.to_datetime(data_usdrub['Date'])
data_brent['Date'] = pd.to_datetime(data_brent['Date'])
data_moex = data_moex.rename(columns={'Price':'MOEX'})
data_usdrub = data_usdrub.rename(columns={'Price':'USDRUB'})
data_brent = data_brent.rename(columns={'Price':'BRENT'})
data_moex1 = data_moex[['Date', 'MOEX']]
data_usdrub1 = data_usdrub[['Date', 'USDRUB']]
data_brent1 = data_brent[['Date', 'BRENT']]

In [0]:
data_keyrate = pd.read_excel('keyrate_cbr.xlsx').iloc[::-1].reset_index()
data_liquidity = pd.read_excel('liquidity_cbr.xlsx').iloc[::-1].reset_index()
data_keyrate = data_keyrate.rename(columns={'Дата':'Date'})
data_liquidity = data_liquidity.rename(columns={'Дата':'Date'})

In [0]:
merge1 = pd.merge(data_moex1, data_usdrub1, on = 'Date')
merge2 = pd.merge(merge1, data_brent1, on = 'Date')
merge3 = pd.merge(merge2, data_keyrate, on = 'Date')
merge4 = pd.merge(merge3, data_liquidity, on = 'Date')

In [15]:
economic_data = merge4
economic_data.head()

        Date  ...  Нетто-объем операций Банка России по предоставлению и абсорбированию ликвидности (без учета операций на внутреннем валютном рынке)
0 2017-01-09  ...                                             -604.4
1 2017-01-10  ...                                             -673.7
2 2017-01-11  ...                                              881.7
3 2017-01-12  ...                                              -20.2
4 2017-01-13  ...                                             -289.7

[5 rows x 21 columns]